import './product.dart';
import 'package:flutter/cupertino.dart';
import 'package:flutter/material.dart';

class Brand {
  String id = UniqueKey().toString();
  String name;
  String logo;
  bool selected;
  double rate;
  List<Product> products;
  Color color;

  Brand(
      {this.name,
      this.logo,
      this.color,
      this.selected,
      this.rate,
      this.products});
}

class BrandsList {
  List<Brand> _list;

  List<Brand> get list => _list;

  BrandsList() {
    _list = [
      new Brand(
          name: 'Wilson',
          logo: 'img/logo-03.svg',
          color: Colors.greenAccent,
          selected: true,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Converse',
          logo: 'img/logo-04.svg',
          color: Colors.cyan,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Umbro',
          logo: 'img/logo-05.svg',
          color: Colors.blueAccent,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Nike',
          logo: 'img/logo-06.svg',
          color: Colors.orange,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Puma',
          logo: 'img/logo-07.svg',
          color: Colors.pinkAccent,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Acer',
          logo: 'img/logo-08.svg',
          color: Colors.deepPurpleAccent,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Reebook',
          logo: 'img/logo-09.svg',
          color: Colors.brown,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Adidas',
          logo: 'img/logo-10.svg',
          color: Colors.blueAccent,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
      new Brand(
          name: 'Crocs',
          logo: 'img/logo-11.svg',
          color: Colors.redAccent,
          selected: false,
          rate: 4.3,
          products: [
            new Product(
                name: 'Zogaa FlameSweater',
                image: 'img/man1.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Polo Shirt Brand Clothing',
                image: 'img/man2.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Polo Shirt for Men',
                image: 'img/man3.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Sport Pants Long Summer',
                image: 'img/man4.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men\'s Hoodies Pullovers Striped',
                image: 'img/man5.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Men Double Breasted Suit Vests',
                image: 'img/man6.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Puimentiua Summer Fashion',
                image: 'img/man7.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
            new Product(
                name: 'Casual Sweater fashion Jacket',
                image: 'img/man8.webp',
                available: 80,
                price: 42.63,
                quantity: 200,
                sales: 2554,
                rate: 3.1,
                discount: 10.5),
          ]),
    ];
  }

  selectById(String id) {
    this._list.forEach((Brand brand) {
      brand.selected = false;
      if (brand.id == id) {
        brand.selected = true;
      }
    });
  }
}
