import '../../config/ui_icons.dart';
import './product.dart';
import 'package:flutter/material.dart';

class Category {
  String id = UniqueKey().toString();
  String name;
  bool selected;
  IconData icon;
  List<Product> products;
  List<SubCategory> subCategories;
  Category({this.name, this.icon, this.selected, this.products});

  void fromJson(Map<String, dynamic> res) {
    this.id = res['id'];
    this.name = res['name'];
    if (res['sub_categories'] != null) {
      subCategories = [];
      for (var x in res['sub_categories']) {
        SubCategory subCategory = SubCategory();
        subCategory.fromJson(x);
        subCategories.add(subCategory);
      }
    }
    if (res['products'] != null) {
      products = [];
      for (var x in res['products']) {
        // Product product=Product(name, image, available, price, quantity, sales, rate, discount)
      }
    }
  }
}

class SubCategory {
  String id = UniqueKey().toString();
  String name;
  bool selected;
  List<Product> products;

  SubCategory({this.name, this.selected, this.products});
  void fromJson(Map<String, dynamic> data) {
    this.id = data['id'];
    this.name = data['name'];
  }
}

class CategoriesList {
  List<Category> _list;

  List<Category> get list => _list;

  CategoriesList() {
    this._list = [
      new Category('Man', UiIcons.shoe_1, true, [
        new Product(
            name: 'Zogaa FlameSweater',
            image: 'img/man1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Polo Shirt Brand Clothing',
            image: 'img/man2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Polo Shirt for Men',
            image: 'img/man3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Sport Pants Long Summer',
            image: 'img/man4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Hoodies Pullovers Striped',
            image: 'img/man5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Double Breasted Suit Vests',
            image: 'img/man6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Puimentiua Summer Fashion',
            image: 'img/man7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Casual Sweater fashion Jacket',
            image: 'img/man8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Women', UiIcons.shoe, false, [
        new Product(
            name: 'Summer Fashion Women Dress',
            image: 'img/pro5.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Women Half Sleeve',
            image: 'img/pro6.webp',
            available: 60,
            price: 94.36,
            quantity: 200,
            sales: 42,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Elegant Plaid Dresses Women Fashion',
            image: 'img/pro7.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Maxi Dress For Women Summer',
            image: 'img/pro1.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Black Checked Retro Hepburn Style',
            image: 'img/pro2.webp',
            available: 60,
            price: 94.36,
            quantity: 200,
            sales: 63,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Robe pin up Vintage Dress Autumn',
            image: 'img/pro3.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Elegant Casual Dress',
            image: 'img/pro4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Child', UiIcons.baby_changing, false, [
        new Product(
            name: 'Fashion Baby Sequins Party Dance Ballet',
            image: 'img/baby1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Children Martin Boots PU Leather',
            image: 'img/baby2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Baby Boys Denim Jacket',
            image: 'img/baby3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Mom and Daughter Matching Women',
            image: 'img/baby4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Unicorn Pajamas Winter Flannel Family',
            image: 'img/baby5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Party Decorations Kids',
            image: 'img/baby6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Car', UiIcons.car_1, false, [
        new Product(
            name: 'Yosoo Knee pad Elastic',
            image: 'img/sport4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Hand Grip Finger Strength',
            image: 'img/sport5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Knee Sl:eeves',
            image: 'img/sport6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Brothock Professional basketball socks',
            image: 'img/sport7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'New men s running trousers',
            image: 'img/sport8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Cotton Elastic Hand Arthritis',
            image: 'img/sport9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Half Finger Outdoor Sports',
            image: 'img/sport10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Fourniture', UiIcons.living_room, false, [
        new Product(
            name: 'Cooking Tools Set Premium',
            image: 'img/home1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reusable Metal Drinking Straws',
            image: 'img/home2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Absorbent Towel Face',
            image: 'img/home3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Pair Heat Resistant Thick Silicone',
            image: 'img/home4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Steel Cutlery Set Gold Cutlery',
            image: 'img/home7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Silicone Kitchen Organizer Insulated ',
            image: 'img/home8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Non Stick Wooden Handle Silicone ',
            image: 'img/home9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Foldable Silicone Colander Fruit Vegetable',
            image: 'img/home10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Watch', UiIcons.watch, false, [
        new Product(
            name: 'Men Wrist Watch Stainless',
            image: 'img/watch1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reef Tiger RT Mens Sport Watches',
            image: 'img/watch2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Sport watch Waterproof',
            image: 'img/watch3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Sport Watch Black Military',
            image: 'img/watch4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Digital Waterproof Wrist Watch',
            image: 'img/watch5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Digital Display Bracelet Watch',
            image: 'img/watch6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Sports Watch Silicone Watchband',
            image: 'img/watch7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Fashion Waterproof Men Digital Watches',
            image: 'img/watch8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Alarm Waterproof Sports Army',
            image: 'img/watch9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Media', UiIcons.home_cinema, false, [
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Steel Cutlery Set Gold Cutlery',
            image: 'img/home7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Silicone Kitchen Organizer Insulated ',
            image: 'img/home8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Non Stick Wooden Handle Silicone ',
            image: 'img/home9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Foldable Silicone Colander Fruit Vegetable',
            image: 'img/home10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Sport', UiIcons.sport, false, [
        new Product(
            name: 'Back Shoulder Posture Correction',
            image: 'img/sport1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Ankle Support Brace Elasticity',
            image: 'img/sport2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Women Swimming Goggles',
            image: 'img/sport3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Yosoo Knee pad Elastic',
            image: 'img/sport4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Hand Grip Finger Strength',
            image: 'img/sport5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Knee Sleeves',
            image: 'img/sport6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Brothock Professional basketball socks',
            image: 'img/sport7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'New men s running trousers',
            image: 'img/sport8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Cotton Elastic Hand Arthritis',
            image: 'img/sport9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Half Finger Outdoor Sports',
            image: 'img/sport10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Travel', UiIcons.tent, false, [
        new Product(
            name: 'Cooking Tools Set Premium',
            image: 'img/home1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reusable Metal Drinking Straws',
            image: 'img/home2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Absorbent Towel Face',
            image: 'img/home3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Pair Heat Resistant Thick Silicone',
            image: 'img/home4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Steel Cutlery Set Gold Cutlery',
            image: 'img/home7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Silicone Kitchen Organizer Insulated ',
            image: 'img/home8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Non Stick Wooden Handle Silicone ',
            image: 'img/home9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Foldable Silicone Colander Fruit Vegetable',
            image: 'img/home10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Tool', UiIcons.tool, false, [
        new Product(
            name: 'Men Wrist Watch Stainless',
            image: 'img/watch1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reef Tiger RT Mens Sport Watches',
            image: 'img/watch2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Sport watch Waterproof',
            image: 'img/watch3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Sport Watch Black Military',
            image: 'img/watch4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Digital Waterproof Wrist Watch',
            image: 'img/watch5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Digital Display Bracelet Watch',
            image: 'img/watch6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Sports Watch Silicone Watchband',
            image: 'img/watch7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Fashion Waterproof Men Digital Watches',
            image: 'img/watch8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Alarm Waterproof Sports Army',
            image: 'img/watch9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Game', UiIcons.game, false, [
        new Product(
            name: 'Back Shoulder Posture Correction',
            image: 'img/sport1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Ankle Support Brace Elasticity',
            image: 'img/sport2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Women Swimming Goggles',
            image: 'img/sport3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Yosoo Knee pad Elastic',
            image: 'img/sport4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Hand Grip Finger Strength',
            image: 'img/sport5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Knee Sleeves',
            image: 'img/sport6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Brothock Professional basketball socks',
            image: 'img/sport7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'New men s running trousers',
            image: 'img/sport8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Cotton Elastic Hand Arthritis',
            image: 'img/sport9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Half Finger Outdoor Sports',
            image: 'img/sport10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new Category('Home', UiIcons.vacuum, false, [
        new Product(
            name: 'Cooking Tools Set Premium',
            image: 'img/home1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reusable Metal Drinking Straws',
            image: 'img/home2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Absorbent Towel Face',
            image: 'img/home3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Pair Heat Resistant Thick Silicone',
            image: 'img/home4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Steel Cutlery Set Gold Cutlery',
            image: 'img/home7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Silicone Kitchen Organizer Insulated ',
            image: 'img/home8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Non Stick Wooden Handle Silicone ',
            image: 'img/home9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Foldable Silicone Colander Fruit Vegetable',
            image: 'img/home10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
    ];
  }

  selectById(String id) {
    this._list.forEach((Category category) {
      category.selected = false;
      if (category.id == id) {
        category.selected = true;
      }
    });
  }

  void clearSelection() {
    _list.forEach((category) {
      category.selected = false;
    });
  }
}

class SubCategoriesList {
  List<SubCategory> _list;

  List<SubCategory> get list => _list;

  SubCategoriesList() {
    this._list = [
      new SubCategory('Sh', true, [
        new Product(
            name: 'Zogaa FlameSweater',
            image: 'img/man1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Polo Shirt Brand Clothing',
            image: 'img/man2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Polo Shirt for Men',
            image: 'img/man3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Sport Pants Long Summer',
            image: 'img/man4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Hoodies Pullovers Striped',
            image: 'img/man5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Double Breasted Suit Vests',
            image: 'img/man6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Puimentiua Summer Fashion',
            image: 'img/man7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Casual Sweater fashion Jacket',
            image: 'img/man8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Sweater', false, [
        new Product(
            name: 'Summer Fashion Women Dress',
            image: 'img/pro5.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Women Half Sleeve',
            image: 'img/pro6.webpavailable:',
            available: 60,
            price: 94.36,
            quantity: 200,
            sales: 42,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Elegant Plaid Dresses Women Fashion',
            image: 'img/pro7.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Maxi Dress For Women Summer',
            image: 'img/pro1.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Black Checked Retro Hepburn Style',
            image: 'img/pro2.webp',
            available: 60,
            price: 94.36,
            quantity: 200,
            sales: 63,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Robe pin up Vintage Dress Autumn',
            image: 'img/pro3.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Elegant Casual Dress',
            image: 'img/pro4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Jacket', false, [
        new Product(
            name: 'Fashion Baby Sequins Party Dance Ballet',
            image: 'img/baby1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Children Martin Boots PU Leather',
            image: 'img/baby2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Baby Boys Denim Jacket',
            image: 'img/baby3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Mom and Daughter Matching Women',
            image: 'img/baby4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Unicorn Pajamas Winter Flannel Family',
            image: 'img/baby5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Party Decorations Kids',
            image: 'img/baby6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Socks', false, [
        new Product(
            name: 'Yosoo Knee pad Elastic',
            image: 'img/sport4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Hand Grip Finger Strength',
            image: 'img/sport5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Knee Sleeves',
            image: 'img/sport6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Brothock Professional basketball socks',
            image: 'img/sport7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'New men s running trousers',
            image: 'img/sport8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Cotton Elastic Hand Arthritis',
            image: 'img/sport9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Half Finger Outdoor Sports',
            image: 'img/sport10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Trousers', false, [
        new Product(
            name: 'Cooking Tools Set Premium',
            image: 'img/home1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reusable Metal Drinking Straws',
            image: 'img/home2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Absorbent Towel Face',
            image: 'img/home3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Pair Heat Resistant Thick Silicone',
            image: 'img/home4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Shirt', true, [
        new Product(
            name: 'Zogaa FlameSweater',
            image: 'img/man1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Polo Shirt Brand Clothing',
            image: 'img/man2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Polo Shirt for Men',
            image: 'img/man3.webp',
            quantity: 80,
            price: 42.63,
            available: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Sport Pants Long Summer',
            image: 'img/man4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men\'s Hoodies Pullovers Striped',
            image: 'img/man5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Men Double Breasted Suit Vests',
            image: 'img/man6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Puimentiua Summer Fashion',
            image: 'img/man7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Casual Sweater fashion Jacket',
            image: 'img/man8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Sweater', false, [
        new Product(
            name: 'Summer Fashion Women Dress',
            image: 'img/pro5.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Women Half Sleeve',
            image: 'img/pro6.webp',
            available: 60,
            price: 94.36,
            quantity: 200,
            sales: 42,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Elegant Plaid Dresses Women Fashion',
            image: 'img/pro7.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Maxi Dress For Women Summer',
            image: 'img/pro1.webp',
            available: 25,
            price: 19.64,
            quantity: 200,
            sales: 130,
            rate: 4.3,
            discount: 12.1),
        new Product(
            name: 'Black Checked Retro Hepburn Style',
            image: 'img/pro2.webp',
            available: 60,
            price: 94.6,
            quantity: 200,
            sales: 63,
            rate: 5.0,
            discount: 20.2),
        new Product(
            name: 'Robe pin up Vintage Dress Autumn',
            image: 'img/pro3.webp',
            available: 10,
            price: 15.73,
            quantity: 200,
            sales: 415,
            rate: 4.9,
            discount: 15.3),
        new Product(
            name: 'Elegant Casual Dress',
            image: 'img/pro4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Jacket', false, [
        new Product(
            name: 'Fashion Baby Sequins Party Dance Ballet',
            image: 'img/baby1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Children Martin Boots PU Leather',
            image: 'img/baby2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Baby Boys Denim Jacket',
            image: 'img/baby3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Mom and Daughter Matching Women',
            image: 'img/baby4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Unicorn Pajamas Winter Flannel Family',
            image: 'img/baby5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Party Decorations Kids',
            image: 'img/baby6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Socks', false, [
        new Product(
            name: 'Yosoo Knee pad Elastic',
            image: 'img/sport4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Hand Grip Finger Strength',
            image: 'img/sport5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Knee Sleeves',
            image: 'img/sport6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Brothock Professional basketball socks',
            image: 'img/sport7.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'New men s running trousers',
            image: 'img/sport8.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Cotton Elastic Hand Arthritis',
            image: 'img/sport9.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Spring Half Finger Outdoor Sports',
            image: 'img/sport10.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
      new SubCategory('Trousers', false, [
        new Product(
            name: 'Cooking Tools Set Premium',
            image: 'img/home1.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Reusable Metal Drinking Straws',
            image: 'img/home2.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Absorbent Towel Face',
            image: 'img/home3.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Pair Heat Resistant Thick Silicone',
            image: 'img/home4.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Electric Mosquito Killer Lamp',
            image: 'img/home5.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Terrarium Hydroponic Plant Vases',
            image: 'img/home6.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
        new Product(
            name: 'Adjustable Sprinkler Plastic Water Sprayer ',
            image: 'img/home11.webp',
            available: 80,
            price: 42.63,
            quantity: 200,
            sales: 2554,
            rate: 3.1,
            discount: 10.5),
      ]),
    ];
  }

  selectById(String id) {
    this._list.forEach((SubCategory subCategory) {
      subCategory.selected = false;
      if (subCategory.id == id) {
        subCategory.selected = true;
      }
    });
  }

  void clearSelection() {
    _list.forEach((category) {
      category.selected = false;
    });
  }
}
